const CONTEXT_FALLBACK_BLOCKED_ERROR_CODES = new Set([
  'PROVIDER_REQUEST_CANCELLED',
  'SPOTIFY_AUTH_EXPIRED',
  'SPOTIFY_AUTH_REFRESH_FAILED',
  'SPOTIFY_AUTH_SCOPE_CHANGED',
  'SPOTIFY_NO_ACTIVE_DEVICE',
  'SPOTIFY_PERMISSION_DENIED',
  'SPOTIFY_PLAYBACK_TARGET_REQUIRED',
  'SPOTIFY_PREMIUM_REQUIRED',
  'SPOTIFY_REQUEST_CANCELLED',
]);

export const PLAYBACK_ACTION_PRIMARY_REFRESH_DELAY_MS = 700;
export const PLAYBACK_ACTION_FOLLOWUP_REFRESH_DELAY_MS = 1800;

export const shouldFallbackToTrackPlayback = (errorInfo = {}) => {
  const code = errorInfo?.code || '';
  return Boolean(code) && !CONTEXT_FALLBACK_BLOCKED_ERROR_CODES.has(code);
};
